/**
 *
 *  Roles.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Roles.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::test;

const std::string Roles::Cols::_role_id = "\"role_id\"";
const std::string Roles::Cols::_role_name = "\"role_name\"";
const std::string Roles::primaryKeyName = "role_id";
const bool Roles::hasPrimaryKey = true;
const std::string Roles::tableName = "\"roles\"";

const std::vector<typename Roles::MetaData> Roles::metaData_={
{"role_id","int32_t","integer",4,1,1,1},
{"role_name","std::string","character varying",50,0,0,1}
};
const std::string &Roles::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Roles::Roles(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["role_id"].isNull())
        {
            roleId_=std::make_shared<int32_t>(r["role_id"].as<int32_t>());
        }
        if(!r["role_name"].isNull())
        {
            roleName_=std::make_shared<std::string>(r["role_name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            roleId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            roleName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Roles::Roles(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            roleId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            roleName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Roles::Roles(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("role_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["role_id"].isNull())
        {
            roleId_=std::make_shared<int32_t>((int32_t)pJson["role_id"].asInt64());
        }
    }
    if(pJson.isMember("role_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["role_name"].isNull())
        {
            roleName_=std::make_shared<std::string>(pJson["role_name"].asString());
        }
    }
}

void Roles::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            roleId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            roleName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Roles::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("role_id"))
    {
        if(!pJson["role_id"].isNull())
        {
            roleId_=std::make_shared<int32_t>((int32_t)pJson["role_id"].asInt64());
        }
    }
    if(pJson.isMember("role_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["role_name"].isNull())
        {
            roleName_=std::make_shared<std::string>(pJson["role_name"].asString());
        }
    }
}

const int32_t &Roles::getValueOfRoleId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(roleId_)
        return *roleId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Roles::getRoleId() const noexcept
{
    return roleId_;
}
void Roles::setRoleId(const int32_t &pRoleId) noexcept
{
    roleId_ = std::make_shared<int32_t>(pRoleId);
    dirtyFlag_[0] = true;
}
const typename Roles::PrimaryKeyType & Roles::getPrimaryKey() const
{
    assert(roleId_);
    return *roleId_;
}

const std::string &Roles::getValueOfRoleName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(roleName_)
        return *roleName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Roles::getRoleName() const noexcept
{
    return roleName_;
}
void Roles::setRoleName(const std::string &pRoleName) noexcept
{
    roleName_ = std::make_shared<std::string>(pRoleName);
    dirtyFlag_[1] = true;
}
void Roles::setRoleName(std::string &&pRoleName) noexcept
{
    roleName_ = std::make_shared<std::string>(std::move(pRoleName));
    dirtyFlag_[1] = true;
}

void Roles::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Roles::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "role_name"
    };
    return inCols;
}

void Roles::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getRoleName())
        {
            binder << getValueOfRoleName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Roles::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Roles::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getRoleName())
        {
            binder << getValueOfRoleName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Roles::toJson() const
{
    Json::Value ret;
    if(getRoleId())
    {
        ret["role_id"]=getValueOfRoleId();
    }
    else
    {
        ret["role_id"]=Json::Value();
    }
    if(getRoleName())
    {
        ret["role_name"]=getValueOfRoleName();
    }
    else
    {
        ret["role_name"]=Json::Value();
    }
    return ret;
}

std::string Roles::toString() const
{
    return toJson().toStyledString();
}

Json::Value Roles::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getRoleId())
            {
                ret[pMasqueradingVector[0]]=getValueOfRoleId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRoleName())
            {
                ret[pMasqueradingVector[1]]=getValueOfRoleName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getRoleId())
    {
        ret["role_id"]=getValueOfRoleId();
    }
    else
    {
        ret["role_id"]=Json::Value();
    }
    if(getRoleName())
    {
        ret["role_name"]=getValueOfRoleName();
    }
    else
    {
        ret["role_name"]=Json::Value();
    }
    return ret;
}

bool Roles::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("role_id"))
    {
        if(!validJsonOfField(0, "role_id", pJson["role_id"], err, true))
            return false;
    }
    if(pJson.isMember("role_name"))
    {
        if(!validJsonOfField(1, "role_name", pJson["role_name"], err, true))
            return false;
    }
    else
    {
        err="The role_name column cannot be null";
        return false;
    }
    return true;
}
bool Roles::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Roles::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("role_id"))
    {
        if(!validJsonOfField(0, "role_id", pJson["role_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("role_name"))
    {
        if(!validJsonOfField(1, "role_name", pJson["role_name"], err, false))
            return false;
    }
    return true;
}
bool Roles::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Roles::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
